export const serv_constants = {
  RIS_CODE_ERR: -99,
  RIS_CODE_EMAIL_ALREADY_VERIFIED: -5,
  RIS_CODE_EMAIL_VERIFIED: 1,
  RIS_CODE_OK: 1,

  RIS_CODE_LOGIN_ERR_GENERIC: -20,
  RIS_CODE_LOGIN_ERR: -10,
  RIS_CODE_LOGIN_OK: 1
}
